apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: qserv
    instance: qserv-dev
    pvc_name: qserv-data-qserv-dev-worker-26
  name: pv-qserv-data-qserv-dev-worker-26
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  local:
    path: /qserv/qserv-dev/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - lsst-qserv-db27
  persistentVolumeReclaimPolicy: Retain
  storageClassName: qserv-local-storage
  volumeMode: Filesystem
