apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qserv-data-qserv-dev-worker-9
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  selector:
    matchLabels:
      pvc_name: qserv-data-qserv-dev-worker-9
  storageClassName: qserv-local-storage
  volumeMode: Filesystem
