apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: qserv
    instance: qserv-prod
  name: qserv-data-qserv-prod-repl-db-0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  selector:
    matchLabels:
      pvc_name: qserv-data-qserv-prod-repl-db-0
  storageClassName: qserv-local-storage
  volumeMode: Filesystem
