apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: qserv
    instance: qserv-dev
  name: qserv-data-qserv-dev-worker-17
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  selector:
    matchLabels:
      pvc_name: qserv-data-qserv-dev-worker-17
  storageClassName: qserv-local-storage
  volumeMode: Filesystem
