sudo: required
language: go
dist: xenial

go:
- 1.13.4

before_script:
  - ./install-operator-sdk.sh
  - git clone --depth 1 -b "v0.5.1" --single-branch https://github.com/k8s-school/kind-travis-ci.git
  - ./kind-travis-ci/kind/k8s-create.sh
  - export KUBECONFIG="$(kind get kubeconfig-path --name="kind")"
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:
  - ./build.sh
  - ./deploy.sh
  - ./wait-operator-ready.sh
  - kubectl apply -k base
  - ./wait-qserv-ready.sh 
  - kubectl get all,endpoints,cm,pvc,pv -o wide
  - ./run-integration-tests.sh

after_success:
  - echo "Push qserv-operator image to Docker Hub"
