sudo: required
language: go
dist: xenial

go:
- 1.13.4

before_script:
  - ./install-operator-sdk.sh
  - git clone --depth 1 -b "v0.6.0" --single-branch https://github.com/k8s-school/kind-travis-ci.git
  - ./kind-travis-ci/kind/k8s-create.sh -s
  - cp env.example.sh env.sh

script:
  - ./build.sh
  - ./deploy.sh
  - ./wait-operator-ready.sh
  - kubectl apply -k base
  - ./wait-qserv-ready.sh 
  - kubectl get all,endpoints,cm,pvc,pv -o wide
  - ./run-integration-tests.sh
