apiVersion: qserv.lsst.org/v1alpha1
kind: Qserv
metadata:
  name: qserv
spec:
  storageclass: "standard"
  storagecapacity: "1Gi"
  worker:
    replicas: 2
    image: "qserv/qserv:f724c3cdf"
  replication:
      image: "qserv/replica:tools-w.2018.16-1120-g3904899"
      dbimage: "mariadb:10.2.16"
  xrootd:
    image: "qserv/qserv:9701693"
